export const CATEGORIES_LOAD_INIT = "CATEGORIES_LOAD_INIT";
export const CATEGORIES_LOAD_SUCCEED = "CATEGORIES_LOAD_SUCCEED";
export const CATEGORIES_LOAD_FAILED = "CATEGORIES_LOAD_FAILED";

export const RECIPES_LOAD_INIT = "RECIPES_LOAD_INIT";
export const RECIPES_LOAD_SUCCEED = "RECIPES_LOAD_SUCCEED";
export const RECIPES_LOAD_FAILED = "RECIPES_LOAD_FAILED";

export const RECIPE_LOAD_INIT = "RECIPE_LOAD_INIT";
export const RECIPE_LOAD_SUCCEED = "RECIPE_LOAD_SUCCEED";
export const RECIPE_LOAD_FAILED = "RECIPE_LOAD_FAILED";

export const ADD_TO_FAV = "ADD_TO_FAV";
export const REMOVE_FROM_FAV = "REMOVE_FROM_FAV";
